// ─── CHRONO RALLYE RACE — DONNÉES DES RALLYES ──────────────────────────────────
// Un objet par rallye. Benjamin met à jour ce fichier chaque week-end :
//   1) avant le rallye  : engagés, classes, coûts, spéciales + horaires de départ
//   2) pendant le rallye : "resultats" au fur et à mesure des spéciales
// Résultat d'un équipage sur une spéciale = son CLASSEMENT DANS SA CLASSE (nombre),
// ou un statut : "Ab" (abandon) | "Tf" (temps forfaitaire) | "Fo" (forfait avant départ).
// statut : 'a_venir' (coquille, non jouable) -> 'ouvert' (entry list saisie) -> 'termine'.
// Horaires : heure française (offset +02:00 en été).
'use strict';

const RALLYES = [
  // ═══════════════════════════════════════════════════════════════════════════
  //  CALENDRIER WRC 2026 — 14 manches.
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: 'monte-carlo-2026',
    nom: 'Rallye Monte-Carlo 2026',
    dates: '22–25 janvier 2026',
    lieu: 'Monaco / Gap',
    surface: 'Asphalte / Neige',
    championnat: 'WRC 2026',
    fuseau: 'Europe/Paris',
    statut: 'termine',
    classes: {},
    cloture: null,
    speciales: [],
    engages: [],
    voitures: [],
    resultats: {},
  },
  {
    id: 'suede-2026',
    nom: 'Rally Sweden 2026',
    dates: '12–15 février 2026',
    lieu: 'Umeå, Suède',
    surface: 'Neige',
    championnat: 'WRC 2026',
    fuseau: 'Europe/Paris',
    statut: 'termine',
    classes: {},
    cloture: null,
    speciales: [],
    engages: [],
    voitures: [],
    resultats: {},
  },
  {
    id: 'kenya-2026',
    nom: 'Safari Rally Kenya 2026',
    dates: '12–15 mars 2026',
    lieu: 'Naivasha, Kenya',
    surface: 'Terre',
    championnat: 'WRC 2026',
    fuseau: 'Europe/Paris',
    statut: 'termine',
    classes: {},
    cloture: null,
    speciales: [],
    engages: [],
    voitures: [],
    resultats: {},
  },
  {
    id: 'croatie-2026',
    nom: 'Croatia Rally 2026',
    dates: '09–12 avril 2026',
    lieu: 'Zagreb, Croatie',
    surface: 'Asphalte',
    championnat: 'WRC 2026',
    fuseau: 'Europe/Paris',
    statut: 'termine',
    classes: {},
    cloture: null,
    speciales: [],
    engages: [],
    voitures: [],
    resultats: {},
  },
  {
    id: 'canaries-2026',
    nom: 'Rally Islas Canarias 2026',
    dates: '23–26 avril 2026',
    lieu: 'Îles Canaries, Espagne',
    surface: 'Asphalte',
    championnat: 'WRC 2026',
    fuseau: 'Europe/Paris',
    statut: 'termine',
    classes: {},
    cloture: null,
    speciales: [],
    engages: [],
    voitures: [],
    resultats: {},
  },
  {
    id: 'portugal-2026',
    nom: 'Vodafone Rally de Portugal 2026',
    dates: '07–10 mai 2026',
    lieu: 'Matosinhos, Portugal',
    surface: 'Terre',
    championnat: 'WRC 2026',
    fuseau: 'Europe/Paris',
    statut: 'termine',
    classes: {},
    cloture: null,
    speciales: [],
    engages: [],
    voitures: [],
    resultats: {},
  },
  {
    id: 'japon-2026',
    nom: 'Rally Japan 2026',
    dates: '28–31 mai 2026',
    lieu: 'Aichi / Gifu, Japon',
    surface: 'Asphalte',
    championnat: 'WRC 2026',
    fuseau: 'Europe/Paris',
    statut: 'termine',
    classes: {},
    cloture: null,
    speciales: [],
    engages: [],
    voitures: [],
    resultats: {},
  },
  {
    id: 'acropole-2026',
    nom: 'EKO Acropolis Rally Greece 2026',
    dates: '25–28 juin 2026',
    lieu: 'Lamia, Grèce',
    surface: 'Terre',
    championnat: 'WRC 2026',
    fuseau: 'Europe/Paris',
    statut: 'termine',
    classes: {},
    cloture: null,
    speciales: [],
    engages: [],
    voitures: [],
    resultats: {},
  },

  // ═══════════════════════════════════════════════════════════════════════════
  //  MANCHE 9 — Delfi Rally Estonia 2026 (OUVERT).
  //  Coûts = PROPOSITION provisoire (à remplacer par l'Excel des crédits).
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: 'estonie-2026',
    nom: 'Delfi Rally Estonia 2026',
    dates: '16–19 juillet 2026',
    lieu: 'Tartu, Estonie',
    surface: 'Terre',
    championnat: 'WRC 2026',
    fuseau: 'Europe/Paris',
    statut: 'ouvert',

    // Engagés par classe en début de rallye (= abscisse du tableau bonus/malus).
    classes: { RC1: 11, RC2: 27, RC3: 12, RC4: 1 },

    // Clôture des écuries = départ ES1 = vendredi 17/7 12:03 heure française (13:03 en Estonie).
    cloture: '2026-07-17T12:03:00+02:00',

    // base = km × 36 s (≈ 100 km/h). Horaires depart en heure française (+02:00).
    speciales: [
      { code: 'ES1',  nom: 'Raanitsa 1',    km: 21.45, base: 772.2, depart: '2026-07-17T12:03:00+02:00' },
      { code: 'ES2',  nom: 'Karaski 1',     km: 11.97, base: 430.9, depart: '2026-07-17T12:56:00+02:00' },
      { code: 'ES3',  nom: 'Kanepi 1',      km: 17.43, base: 627.5, depart: '2026-07-17T13:49:00+02:00' },
      { code: 'ES4',  nom: 'Raanitsa 2',    km: 21.45, base: 772.2, depart: '2026-07-17T15:46:00+02:00' },
      { code: 'ES5',  nom: 'Karaski 2',     km: 11.97, base: 430.9, depart: '2026-07-17T16:39:00+02:00' },
      { code: 'ES6',  nom: 'Kanepi 2',      km: 17.43, base: 627.5, depart: '2026-07-17T17:32:00+02:00' },
      { code: 'ES7',  nom: 'Elva Linn',     km:  1.72, base:  61.9, depart: '2026-07-17T18:35:00+02:00' },
      { code: 'ES8',  nom: 'Peipsiääre 1',  km: 24.35, base: 876.6, depart: '2026-07-18T08:56:00+02:00' },
      { code: 'ES9',  nom: 'Mustvee 1',     km: 10.67, base: 384.1, depart: '2026-07-18T09:49:00+02:00' },
      { code: 'ES10', nom: 'Peipsiääre 2',  km: 24.35, base: 876.6, depart: '2026-07-18T11:10:00+02:00' },
      { code: 'ES11', nom: 'Mustvee 2',     km: 10.67, base: 384.1, depart: '2026-07-18T12:03:00+02:00' },
      { code: 'ES12', nom: 'Kambja 1',      km: 23.74, base: 854.6, depart: '2026-07-18T14:48:00+02:00' },
      { code: 'ES13', nom: 'Otepää 1',      km: 15.16, base: 545.8, depart: '2026-07-18T16:05:00+02:00' },
      { code: 'ES14', nom: 'Kambja 2',      km: 23.74, base: 854.6, depart: '2026-07-18T16:58:00+02:00' },
      { code: 'ES15', nom: 'Otepää 2',      km: 15.16, base: 545.8, depart: '2026-07-18T18:05:00+02:00' },
      { code: 'ES16', nom: 'Tartu Vald',    km:  1.76, base:  63.4, depart: '2026-07-18T19:35:00+02:00' },
      { code: 'ES17', nom: 'Kääriku 1',     km: 24.39, base: 878.0, depart: '2026-07-19T10:05:00+02:00' },
      { code: 'ES18', nom: 'Kääriku 2',     km: 24.39, base: 878.0, depart: '2026-07-19T12:15:00+02:00' },
    ],

    // 51 engagés. cout : 10/20/30/40 selon la performance attendue DANS SA CLASSE (À VALIDER via Excel).
    engages: [
      { id:'1',  pilote:'Sébastien Ogier',       copilote:'Vincent Landais',     classe:'RC1', modele:'Toyota GR Yaris Rally1', cout:40 },
      { id:'4',  pilote:'Esapekka Lappi',        copilote:'Enni Mälkönen',       classe:'RC1', modele:'Hyundai i20 N Rally1',   cout:30 },
      { id:'5',  pilote:'Sami Pajari',           copilote:'Marko Salminen',      classe:'RC1', modele:'Toyota GR Yaris Rally1', cout:30 },
      { id:'11', pilote:'Thierry Neuville',      copilote:'Martijn Wydaeghe',    classe:'RC1', modele:'Hyundai i20 N Rally1',   cout:40 },
      { id:'16', pilote:'Adrien Fourmaux',       copilote:'Alexandre Coria',     classe:'RC1', modele:'Hyundai i20 N Rally1',   cout:30 },
      { id:'18', pilote:'Takamoto Katsuta',      copilote:'Aaron Johnston',      classe:'RC1', modele:'Toyota GR Yaris Rally1', cout:30 },
      { id:'22', pilote:'Mārtiņš Sesks',         copilote:'Renārs Francis',      classe:'RC1', modele:'Ford Puma Rally1',       cout:20 },
      { id:'33', pilote:'Elfyn Evans',           copilote:'Scott Martin',        classe:'RC1', modele:'Toyota GR Yaris Rally1', cout:40 },
      { id:'55', pilote:'Josh McErlean',         copilote:'Eoin Treacy',         classe:'RC1', modele:'Ford Puma Rally1',       cout:10 },
      { id:'95', pilote:'Jon Armstrong',         copilote:'Shane Byrne',         classe:'RC1', modele:'Ford Puma Rally1',       cout:10 },
      { id:'99', pilote:'Oliver Solberg',        copilote:'Elliott Edmondson',   classe:'RC1', modele:'Toyota GR Yaris Rally1', cout:20 },

      { id:'20', pilote:'Roope Korhonen',        copilote:'Anssi Viinikka',      classe:'RC2', modele:'Toyota GR Yaris Rally2', cout:30 },
      { id:'21', pilote:'Teemu Suninen',         copilote:'Janni Hussi',         classe:'RC2', modele:'Toyota GR Yaris Rally2', cout:40 },
      { id:'23', pilote:'Robert Virves',         copilote:'Jakko Viilo',         classe:'RC2', modele:'Škoda Fabia RS Rally2',  cout:40 },
      { id:'24', pilote:'Fau Zaldívar',          copilote:'M. Der Ohannesian',   classe:'RC2', modele:'Škoda Fabia RS Rally2',  cout:20 },
      { id:'25', pilote:'Emil Lindholm',         copilote:'G. Morales',          classe:'RC2', modele:'Škoda Fabia RS Rally2',  cout:40 },
      { id:'26', pilote:'Gus Greensmith',        copilote:'Jonas Andersson',     classe:'RC2', modele:'Toyota GR Yaris Rally2', cout:30 },
      { id:'27', pilote:'Jan Solans',            copilote:'Rodrigo Sanjuan',     classe:'RC2', modele:'Škoda Fabia RS Rally2',  cout:40 },
      { id:'28', pilote:'Lauri Joona',           copilote:'A. Linnaketo',        classe:'RC2', modele:'Škoda Fabia RS Rally2',  cout:30 },
      { id:'29', pilote:'Yuki Yamamoto',         copilote:'James Fulton',        classe:'RC2', modele:'Toyota GR Yaris Rally2', cout:20 },
      { id:'30', pilote:'Arthur Pelamourgues',   copilote:'Bastien Pouget',      classe:'RC2', modele:'Hyundai i20 N Rally2',   cout:20 },
      { id:'31', pilote:'Mille Johansson',       copilote:'Johan Grönvall',      classe:'RC2', modele:'Škoda Fabia RS Rally2',  cout:20 },
      { id:'32', pilote:'Giovanni Trentin',      copilote:'P. Ometto',           classe:'RC2', modele:'Škoda Fabia RS Rally2',  cout:20 },
      { id:'34', pilote:'Bernhard ten Brinke',   copilote:'Tom Woodburn',        classe:'RC2', modele:'Toyota GR Yaris Rally2', cout:20 },
      { id:'35', pilote:'Romet Jürgenson',       copilote:'Siim Oja',            classe:'RC2', modele:'Ford Fiesta Rally2',     cout:20 },
      { id:'36', pilote:'Jaspar Vaher',          copilote:'Rait Jansen',         classe:'RC2', modele:'Toyota GR Yaris Rally2', cout:20 },
      { id:'37', pilote:'Mikko Heikkilä',        copilote:'K. Temonen',          classe:'RC2', modele:'Škoda Fabia RS Rally2',  cout:30 },
      { id:'38', pilote:'Patrick Enok',          copilote:'Silver Simm',         classe:'RC2', modele:'Škoda Fabia RS Rally2',  cout:10 },
      { id:'39', pilote:'Egon Kaur',             copilote:'Ermo Veltson',        classe:'RC2', modele:'Toyota GR Yaris Rally2', cout:30 },
      { id:'40', pilote:'Karl Martin Volver',    copilote:'Annika Sõna',         classe:'RC2', modele:'Toyota GR Yaris Rally2', cout:10 },
      { id:'41', pilote:'Joosep Ralf Nõgene',    copilote:'Aleks Lesk',          classe:'RC2', modele:'Toyota GR Yaris Rally2', cout:10 },
      { id:'42', pilote:'Tuukka Kauppinen',      copilote:'S. Virtanen',         classe:'RC2', modele:'Toyota GR Yaris Rally2', cout:10 },
      { id:'43', pilote:'Takumi Matsushita',     copilote:'Pekka Kelander',      classe:'RC2', modele:'Toyota GR Yaris Rally2', cout:10 },
      { id:'44', pilote:'Shotaro Goto',          copilote:'Jussi Lindberg',      classe:'RC2', modele:'Toyota GR Yaris Rally2', cout:10 },
      { id:'45', pilote:'Johannes Keferböck',    copilote:'Ilka Minor',          classe:'RC2', modele:'Toyota GR Yaris Rally2', cout:10 },
      { id:'46', pilote:'Uğur Soylu',            copilote:'M. Yalçın',           classe:'RC2', modele:'Škoda Fabia RS Rally2',  cout:10 },
      { id:'59', pilote:'Urmo Aava',             copilote:'Silver Kütt',         classe:'RC2', modele:'Toyota GR Yaris Rally2', cout:20 },
      { id:'61', pilote:'Luca Hoelbling',        copilote:'F. Fiorini',          classe:'RC2', modele:'Škoda Fabia RS Rally2',  cout:10 },

      { id:'48', pilote:'Rio Ogata',             copilote:'M. Korhonen',         classe:'RC3', modele:'Renault Clio Rally3',    cout:30 },
      { id:'49', pilote:'Kanta Yanaguida',       copilote:'J. Koski-Lammi',      classe:'RC3', modele:'Renault Clio Rally3',    cout:20 },
      { id:'50', pilote:'Tymoteusz Abramowski',  copilote:'Jakub Wróbel',        classe:'RC3', modele:'Ford Fiesta Rally3',     cout:20 },
      { id:'51', pilote:'Nataniel Bruun',        copilote:'Pablo Olmos',         classe:'RC3', modele:'Ford Fiesta Rally3',     cout:20 },
      { id:'52', pilote:'Priit Koik',            copilote:'Allan Birjukov',      classe:'RC3', modele:'Renault Clio Rally3',    cout:40 },
      { id:'53', pilote:'Kerem Kazaz',           copilote:'C. Silvestre',        classe:'RC3', modele:'Ford Fiesta Rally3',     cout:10 },
      { id:'54', pilote:'Jarkko Nikara',         copilote:'Tomiya Maekawa',      classe:'RC3', modele:'Renault Clio Rally3',    cout:40 },
      { id:'57', pilote:'Nicolas Otto',          copilote:'Hugo Magalhães',      classe:'RC3', modele:'Ford Fiesta Rally3',     cout:30 },
      { id:'58', pilote:'A. Martínez Merizalde', copilote:'M. Aranguren',        classe:'RC3', modele:'Ford Fiesta Rally3',     cout:10 },
      { id:'60', pilote:'Isak Hatanmaa',         copilote:'D. Kammersgaard',     classe:'RC3', modele:'Ford Fiesta Rally3',     cout:10 },
      { id:'62', pilote:'Esmar-Arnold Unt',      copilote:'Arro Vahtra',         classe:'RC3', modele:'Ford Fiesta Rally3',     cout:10 },
      { id:'63', pilote:'Mika Karppanen',        copilote:'K. Peräläinen',       classe:'RC3', modele:'Renault Clio Rally3',    cout:20 },

      { id:'64', pilote:'Travis Pärs',           copilote:'Allar Heina',         classe:'RC4', modele:'Peugeot 208 Rally4',     cout:20 },
    ],

    // Modèles proposés (1 par écurie). cout = moyenne des coûts des équipages du modèle, ramenée au palier.
    voitures: [
      { modele:'Toyota GR Yaris Rally1', classes:['RC1'], cout:30 },
      { modele:'Hyundai i20 N Rally1',   classes:['RC1'], cout:30 },
      { modele:'Ford Puma Rally1',       classes:['RC1'], cout:10 },
      { modele:'Toyota GR Yaris Rally2', classes:['RC2'], cout:20 },
      { modele:'Škoda Fabia RS Rally2',  classes:['RC2'], cout:20 },
      { modele:'Hyundai i20 N Rally2',   classes:['RC2'], cout:20 },
      { modele:'Ford Fiesta Rally2',     classes:['RC2'], cout:20 },
      { modele:'Renault Clio Rally3',    classes:['RC3'], cout:30 },
      { modele:'Ford Fiesta Rally3',     classes:['RC3'], cout:20 },
      { modele:'Peugeot 208 Rally4',     classes:['RC4'], cout:20 },
    ],

    // Résultats : resultats[idEquipage][codeES] = classement DANS SA CLASSE, ou 'Ab'/'Tf'.
    // À saisir spéciale par spéciale pendant le week-end (ES1 = vendredi 17/7).
    resultats: {},
  },

  // ═══════════════════════════════════════════════════════════════════════════
  //  MANCHES 10 à 14 — à venir (coquilles).
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: 'finlande-2026',
    nom: 'Secto Rally Finland 2026',
    dates: '30 juillet–02 août 2026',
    lieu: 'Jyväskylä, Finlande',
    surface: 'Terre',
    championnat: 'WRC 2026',
    fuseau: 'Europe/Paris',
    statut: 'a_venir',
    classes: {},
    cloture: null,
    speciales: [],
    engages: [],
    voitures: [],
    resultats: {},
  },
  {
    id: 'paraguay-2026',
    nom: 'Ueno Rally del Paraguay 2026',
    dates: '27–30 août 2026',
    lieu: 'Encarnación, Paraguay',
    surface: 'Terre',
    championnat: 'WRC 2026',
    fuseau: 'Europe/Paris',
    statut: 'a_venir',
    classes: {},
    cloture: null,
    speciales: [],
    engages: [],
    voitures: [],
    resultats: {},
  },
  {
    id: 'chili-2026',
    nom: 'Rally Chile Bío Bío 2026',
    dates: '10–13 septembre 2026',
    lieu: 'Concepción, Chili',
    surface: 'Terre',
    championnat: 'WRC 2026',
    fuseau: 'Europe/Paris',
    statut: 'a_venir',
    classes: {},
    cloture: null,
    speciales: [],
    engages: [],
    voitures: [],
    resultats: {},
  },
  {
    id: 'sardaigne-2026',
    nom: 'Rally Italia 2026',
    dates: '01–04 octobre 2026',
    lieu: 'Sardaigne, Italie',
    surface: 'Terre',
    championnat: 'WRC 2026',
    fuseau: 'Europe/Paris',
    statut: 'a_venir',
    classes: {},
    cloture: null,
    speciales: [],
    engages: [],
    voitures: [],
    resultats: {},
  },
  {
    id: 'arabie-saoudite-2026',
    nom: 'Rally Saudi Arabia 2026',
    dates: '12–15 novembre 2026',
    lieu: 'Arabie Saoudite',
    surface: 'Terre',
    championnat: 'WRC 2026',
    fuseau: 'Europe/Paris',
    statut: 'a_venir',
    classes: {},
    cloture: null,
    speciales: [],
    engages: [],
    voitures: [],
    resultats: {},
  },
];

module.exports = { RALLYES };
